name: Start EC2 runner

on:
  workflow_call:
    inputs:
      ec2-instance-type:
        description: EC2 instance type
        type: string
        required: false
        default: t3.small
    outputs:
      label:
        description: "Name of the unique label assigned to the runner"
        value: ${{ jobs.start-runner.outputs.label }}
      ec2-instance-id:
        description: "EC2 Instance Id of the created runner"
        value: ${{ jobs.start-runner.outputs.ec2-instance-id }}

jobs:
  start-runner:
    name: Start EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16 # TODO: update with v2 when available
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0f6c72ce17bd23bb3
          ec2-instance-type: ${{ inputs.ec2-instance-type }}
          subnet-id: subnet-fcf9ffb6
          security-group-id: sg-0c0e690e3d54b7bca
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "ec2-github-runner"},
              {"Key": "Microservice", "Value": "gha"},
              {"Key": "Repository", "Value": "${{ github.repository }}"}
            ]
